### ISSUE TITLE
some error occurred when following the usage steps - Please note that karateFeaturesDir has to be relative to perfiz.yml location.

### ISSUE THREAD

**Issue by auto110** [znsio/perfiz-demo#1]
![image](https://user-images.githubusercontent.com/33770132/112623013-c5b95d00-8e66-11eb-83c9-ad9d1b467d98.png)

**Comment by harikrishnan83** [comment]
@auto110 Thank you for reporting the issue. This was indeed a bug in error logging and it has been fixed in this [commit](https://github.com/znsio/perfiz-cli/commit/ee06b22653517be9089e22e57056e2f68744d23d).

Please delete your current release of Perfiz in your PERFIZ_HOME location and download the latest release [Perfiz 0.0.4](https://github.com/znsio/perfiz/releases/download/0.0.4/perfiz.zip) and this error message should go away.

Not sure why I see there is a exit status 1 after the "Starting Perfiz Docker Containers..." in your screenshot. Can you please confirm you have Docker running and docker-compose setup? Also please share the OS you are using.

Please feel free to report any other issues you run into. Thanks.

**Comment by auto110** [comment]
@harikrishnan83     Thanks for your quickly replay. Yes, I faild to run this, it exits with status 1. 
 
I test this on centos 7 server within my company before getting off work. Now I am at home, so  I need to verify it next week.  

By the way, I remember the Docker and docker-compose are already setup and running.

**Comment by bitlin** [comment]
@harikrishnan83    
**Test environment** 
- CentOS Linux release 7.7.1908 (Core) 
- Docker version 19.03.12, build 48a66213fe
- docker-compose version 1.24.1, build 4667896b

**The error** 

![image](https://user-images.githubusercontent.com/14798891/112777041-ba874c80-9073-11eb-84f0-69ae90e10beb.png)

I set the version to 3.3, then it says "networks.perfiz-network value Additional properties are not allowed ('name' was unexpected)"

![image](https://user-images.githubusercontent.com/14798891/112777303-734d8b80-9074-11eb-85de-a9b0b4c35798.png)

**Comment by harikrishnan83** [comment]
@bitlin Thanks for reporting this. Appreciate your effort taking time to provide screenshots. It really helps.

About the first error message, looks like you may need to upgrade your docker-compose version. I tested the docker-compose.yml with below version.
```shell
$ docker-compose version
docker-compose version 1.28.5, build c4eb3a1f
docker-py version: 4.4.4
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

Setting docker-compose.yml version to 3.3 will not work because, "network" capability was added in docker-compose yml version [3.4](https://docs.docker.com/compose/compose-file/compose-versioning/#version-34).

I suggest you upgrade your docker-compose cli to a more recent version. Or alternatively (if you are unable to upgrade immediately) can you please try setting docker-compose version to 3.4 or more?

Please do report any other issues you run into.

**Comment by auto110** [comment]
@harikrishnan83  It's the same issue if only just only setting docker-compose version to 3.4.  Then, I upgrade the docker-compose cli to the latest version, it works. 
However, it's blocked by pulling cadvisor timeout.
![image](https://user-images.githubusercontent.com/33770132/112791943-131b1180-9095-11eb-990d-0c74b8a2d2a9.png)

**Comment by harikrishnan83** [comment]
@auto110 Many thanks for checking, I will update documentation with docker-compose cli version in pre-requisites.

On the cadvisor issue it can happen when there are network blips. Can you retry running ```perfiz.sh start```, it should pick up where it left of and pull the cadvisor.

**Comment by harikrishnan83** [comment]
@auto110 May I know in which Geography your machine is located? Docker pulls can be slow in some locations as mentioned in this thread https://stackoverflow.com/questions/28957330/acclerate-docker-pull-in-china-asia

**Comment by auto110** [comment]
@harikrishnan83  
![image](https://user-images.githubusercontent.com/33770132/112799004-5b8bfc80-90a0-11eb-8b85-683e0d5780e0.png)

 :)  My machine is located in China.

By the way, my docker version is still Docker version 19.03.12, build 48a66213fe, I just only upgrade my docker-compose version to the latest version.

**Comment by harikrishnan83** [comment]
@auto110 Thanks for confirming that Docker version 19.03.12 works and only docker-compose required the update.

About the timeouts on the docker images, it is interesting that it is getting stuck at cadvisor. I just retested this by deleting my local copy of cadvisor image and it downloaded without any issues. Please check if you need to make any changes to your Docker setup like setting up a mirror etc.

Maybe just to get past this problem for the moment, you can comment out below lines in ```$PERFIZ_HOME/docker-compose.yml```

```shell script
cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8082:8080
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw # This works on Mac
#      - /var/run:/var/run:ro # This may work on Linux
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - perfiz-network
```

You will still see some interesting Gatling graphs on Grafana even without cadvisor.

**Comment by harikrishnan83** [comment]
Closing this issue as we resolved the ```perfiz.sh start``` related issues. @auto110 and @bitlin, please feel free to report any other issues you run into separately. Thanks.
